### PR TITLE
Add User Models

### PR DESCRIPTION
**Pull request by imanebk-github**
We added the BaseModel for our users and created a base class called UserModel and then we extended 3 user classes from it : seller, admin and client.

### CODE REVIEW

**Comment by HanRachid** [comment]
Great work 👍 

The modules prettier and eslint need to be installed as dev dependencies.

**Comment by imanebk-github** [comment]
I modified the changes you requested 👍

-removed Prettier and Eslint form dependencies
-reinstalled them in devDependencies

**Comment by HanRachid** [comment]
LGTM 👍

**Comment by HanRachid** [comment]
Please add documentation to classes and interface

**Pull request merged**
